# Generated by Django 3.2.6 on 2022-01-16 11:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(255)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=20)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.production')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipe.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='production',
            name='production_recipes',
            field=models.ManyToManyField(through='production.ProductionRecipe', to='recipe.Recipe'),
        ),
    ]
