# Generated by Django 3.2.6 on 2022-01-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
        ('recipe', '0002_recipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.ManyToManyField(through='recipe.RecipeIngredient', to='ingredient.Ingredient'),
        ),
    ]
