# Generated by Django 3.2.6 on 2021-12-30 12:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True)),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=70)),
                ('notes', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(255)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='supplier.supplier')),
            ],
        ),
    ]
