# Generated by Django 3.2.6 on 2022-01-13 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20220109_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='notes',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
