# Generated by Django 3.2.6 on 2022-01-13 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
        ('purchase', '0005_alter_purchase_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredient.ingredient'),
        ),
    ]
