# Generated by Django 3.2.6 on 2022-01-16 11:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(255)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdjustmentIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=20)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjustment.adjustment')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredient.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='adjustment',
            name='adjustment_ingredients',
            field=models.ManyToManyField(through='adjustment.AdjustmentIngredient', to='ingredient.Ingredient'),
        ),
    ]
